version: '3'

services:

  git:
    image: bitnami/git:2.36.1
    volumes:
      - git:/git
    command: git clone "https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git" /git

  maven:
    image: maven:3-jdk-7-alpine
    depends_on:
      git:
        condition: service_completed_successfully
    volumes:
      - git:/git
    command: mvn -f /git/pom.xml package

  tomcat:
    image: tomcat:7-jre7-alpine
    restart: always
    depends_on:
      maven:
        condition: service_completed_successfully
    volumes:
      - git:/git
      - ./Config.properties:/usr/local/tomcat/ROOT/Config.properties
    networks:
      - app42
    command: >
      /bin/bash -c "cp /git/target/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/app42.war
      && catalina.sh run"
    ports:
      - "80:8080"

  db:
    image: mariadb:10.7.4
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password
    networks:
      - app42

volumes:
  git:

networks:
  app42: